//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportBoard.Data.DAL
{
    using System;
    
    public enum NotificationTypes : int
    {
        FeedDeletionRequest = 1,
        NewPost = 2,
        NewComment = 3,
        FeedDeletionResponse = 4
    }
}
