//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportBoard.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int PostId { get; set; }
        public System.DateTime PostDate { get; set; }
        public int ImageId { get; set; }
        public string UserId { get; set; }
        public string Description { get; set; }
        public int FeedId { get; set; }
    
        public virtual Feed Feed { get; set; }
    }
}
