//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportBoard.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPreferences
    {
        public string UserId { get; set; }
        public string SortOption { get; set; }
        public string FilterOption { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
